services:
  db:
    image: 'postgres:16.2-alpine'
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_DB=people
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://db:5432/people
      db-username: postgres
      db-password: postgres
    restart: always
    depends_on:
      - db

volumes:
  db-data: